### ISSUE TITLE
Can you support this?

### ISSUE THREAD

**Issue by FlyingYu-Z** [ronniebasak/JStruct#2]
![image](https://user-images.githubusercontent.com/23566361/116667165-74087300-a9ce-11eb-8358-5436a321b9fd.png)

**Comment by ronniebasak** [comment]
Sure. I can. Can you help me write some tests if possible. I am surprised with how many stars it got considering this was probably the only piece of java code I ever wrote on Github.

**Comment by FlyingYu-Z** [comment]
Thank you for reply ! but i found the way to solve it,that't Jython.
![image](https://user-images.githubusercontent.com/23566361/120875850-86cf2280-c5e0-11eb-9f83-3ad7d79d0025.png)

![image](https://user-images.githubusercontent.com/23566361/120875839-7dde5100-c5e0-11eb-9d66-26d720d042bd.png)

Sorry, I don't have time to help you with your test.
If you want to continue to update jstruct, you can refer to Jython to improve it.
